// AUTO-GENERATED by scripts/extract-strings.js — do not edit by hand.
// Regenerated on every build (npm run build) from the site's pages and
// string modules. Add data-i18n to markup or extend the string modules;
// this file picks it all up automatically.

export const SITE_STRINGS = [
  "Find a Coach",
  "For Organisations",
  "For Coaches",
  "Insights",
  "Events",
  "About",
  "Loading…",
  "By",
];

export const TARGET_LANGS = ['de', 'fr', 'it'];
export const SOURCE_LANG = 'en';
