import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const HTML_PAGES = [
  'index.html',
  'find-a-coach.html',
  'for-organisations.html',
  'for-coaches.html',
  'insights.html',
  'article.html',
  'events.html',
  'about.html',
];

// JS modules that render markup with data-i18n via template literals.
const JS_TEMPLATE_FILES = ['js/layout.js', 'js/insights.js', 'js/article.js'];

// Strings rendered dynamically in JS without literal data-i18n markup.
const EXTRA_STRINGS = [
  'Find a Coach',
  'For Organisations',
  'For Coaches',
  'Insights',
  'Events',
  'About',
  'Loading articles…',
  'Loading…',
  'By',
];

const NAMED_ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: '\u00a0',
  mdash: '\u2014', ndash: '\u2013', middot: '\u00b7', rarr: '\u2192',
  larr: '\u2190', copy: '\u00a9', times: '\u00d7', hellip: '\u2026',
  rsquo: '\u2019', lsquo: '\u2018', rdquo: '\u201d', ldquo: '\u201c',
};

function decodeEntities(str) {
  return str
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, n) => String.fromCodePoint(parseInt(n, 16)))
    .replace(/&([a-zA-Z]+);/g, (m, name) => NAMED_ENTITIES[name] ?? m);
}

function extractFromMarkup(source, collect) {
  const textRe = /data-i18n(?:="[^"]*")?[^>]*>([^<]+)</g;
  let m;
  while ((m = textRe.exec(source)) !== null) {
    const text = decodeEntities(m[1]).trim();
    if (text && !text.includes('${')) collect(text);
  }

  const tagRe = /<[^>]*data-i18n-attr="([^"]+)"[^>]*>/g;
  while ((m = tagRe.exec(source)) !== null) {
    const tag = m[0];
    const attrs = m[1].split(',').map((s) => s.trim()).filter(Boolean);
    for (const attr of attrs) {
      const valMatch = tag.match(new RegExp(`\\b${attr}="([^"]*)"`));
      if (valMatch && valMatch[1] && !valMatch[1].includes('${')) {
        collect(decodeEntities(valMatch[1]).trim());
      }
    }
  }
}

function extractHeadStrings(source, collect) {
  const title = source.match(/<title>([^<]+)<\/title>/);
  if (title) collect(decodeEntities(title[1]).trim());
  const desc = source.match(/<meta\s+name="description"\s+content="([^"]*)"/);
  if (desc) collect(decodeEntities(desc[1]).trim());
}

async function main() {
  const strings = [];
  const seen = new Set();
  const collect = (s) => {
    if (s && !seen.has(s)) {
      seen.add(s);
      strings.push(s);
    }
  };

  for (const page of HTML_PAGES) {
    const source = readFileSync(resolve(root, page), 'utf8');
    extractHeadStrings(source, collect);
    extractFromMarkup(source, collect);
  }
  for (const file of JS_TEMPLATE_FILES) {
    extractFromMarkup(readFileSync(resolve(root, file), 'utf8'), collect);
  }

  const { DIRECTORY_UI_STRINGS } = await import(pathToFileURL(resolve(root, 'js/find-a-coach-strings.js')));
  DIRECTORY_UI_STRINGS.forEach(collect);

  const { getAllSurveyStrings } = await import(pathToFileURL(resolve(root, 'js/org-survey-strings.js')));
  getAllSurveyStrings().forEach(collect);

  EXTRA_STRINGS.forEach(collect);

  const body = strings
    .map((s) => `  ${JSON.stringify(s)},`)
    .join('\n');

  const output = `// AUTO-GENERATED by scripts/extract-strings.js — do not edit by hand.
// Regenerated on every build (npm run build) from the site's pages and
// string modules. Add data-i18n to markup or extend the string modules;
// this file picks it all up automatically.

export const SITE_STRINGS = [
${body}
];

export const TARGET_LANGS = ['de', 'fr', 'it'];
export const SOURCE_LANG = 'en';
`;

  writeFileSync(resolve(root, 'js/site-strings.js'), output);
  console.log(`extract-strings: ${strings.length} unique strings written to js/site-strings.js`);
}

main().catch((err) => {
  console.error('extract-strings failed:', err);
  process.exit(1);
});
